### PR TITLE
fix: fix overflow from bit calculation

### LINKED ISSUE #488: [버그] 봇 초대링크 생성기 버그
## 재현방법

> 어떻게하면 발생시킬 수 있나요?
https://koreanbots.dev/calculator
봇 초대링크 생성기에서 채팅채널 권한에 빗금 명령어 사용을 체크하면 버그가 발생됩니다

## 예상되는 정상적인 동작

> 정상이라면 어떻게 되야하나요?
정상적으로 초대가 되야합니다

## 발생한 문제

> 어떤 문제가 발생하나요?
permission코드가 2147483648로 되야하나 앞에 -가 붙어 알 수 없는 permission코드라고 나와서 초대가 불가능합니다

## 빌드 버전

> 클라이언트의 빌드 버전을 알려주세요!
master
v2.1.1

## 사양

> OS 정보와 브라우저의 버전을 알려주세요!
Windows 11 Pro
네이버 웨일 / 버전 3.13.131.36(공식 빌드) (64비트)
## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

### PR DESCRIPTION
**Pull request by SaidBySolo**
maybe close #488 

close #512

### CODE REVIEW

**Review by chul0721 — APPROVED** [review]

File: pages/calculator.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const Calculator:NextPage<CalculatorProps> = ({ query }) => {
 			description: '디스코드 봇 초대링크를 간편하게 생성하세요'
 		}} />
 		<h1 className='text-4xl font-bold mt-2 mb-4'>봇 초대링크 생성기</h1>
-		<div className='text-2xl font-bold inline-flex items-center'>권한: {Object.keys(value).filter(el => value[el]).map(el => Number(el)).reduce((prev, curr) => prev | curr, 0)} 
+		<div className='text-2xl font-bold inline-flex items-center'>권한: {Object.keys(value).filter(el => value[el]).map(el => Number(el)).reduce((prev, curr) => BigInt(prev) | BigInt(curr), BigInt(0))}
```
Comment (chul0721) [inline pages/calculator.tsx:32]: 계산 결과를 String()으로 타이핑 해야될것 같아요.

**Review by chul0721 — CHANGES_REQUESTED** [review]

**Review by chul0721 — APPROVED** [review]

**Comment by SaidBySolo** [comment]
close #512
